spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: 'true'
  application:
    name: pagamentos-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

server:
  port: 0

resilience4j.circuitbreaker:
  instances:
    atualizaPedido:
      slidingWindowSize: 3
      minimumNumberOfCalls: 2
      waitDurationInOpenState: 50s