spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alurafood-pedidos?createDatabaseIfNotExist=true
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: pedidos-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 0